"""Constants for Calendar Signs."""

DOMAIN = "calendarsigns"
DEFAULT_NAME = "Calendar Signs"

# Traditional Astrological Zodiac
TA_NAME = "Traditional Astrological Zodiac"
SIGN_TA_ARIES = "aries"
SIGN_TA_TAURUS = "taurus"
SIGN_TA_GEMINI = "gemini"
SIGN_TA_CANCER = "cancer"
SIGN_TA_LEO = "leo"
SIGN_TA_VIRGO = "virgo"
SIGN_TA_LIBRA = "libra"
SIGN_TA_SCORPIO = "scorpio"
SIGN_TA_SAGITTARIUS = "sagittarius"
SIGN_TA_CAPRICORN = "capricorn"
SIGN_TA_AQUARIUS = "aquarius"
SIGN_TA_PISCES = "pisces"

# Elements
ELEMENT_FIRE = "fire"
ELEMENT_AIR = "air"
ELEMENT_EARTH = "earth"
ELEMENT_WATER = "water"

# Modality
MODALITY_CARDINAL = "cardinal"
MODALITY_FIXED = "fixed"
MODALITY_MUTABLE = "mutable"

# Stone
STONE_OPAL = "opal"
STONE_JASPER = "jasper"
STONE_AGATE = "agate"
STONE_ROSEQUARTZ = "rosequartz"
STONE_CARNELIAN = "carnelian"
STONE_AMETHYST = "amethyst"
STONE_AZURITE = "azurite"
STONE_COPPER = "copper"
STONE_OBSIDIAN = "obsidian"
STONE_QUARTZ = "quartz"
STONE_TURQUOISE = "turquoise"
STONE_JADE = "jade"

# Attributes
ATTR_ELEMENT = "element"
ATTR_MODALITY = "modality"
ATTR_STONE = "stone"

# Japan Zen Signs
JZ_NAME = "Japan Zen Signs"
SIGN_JZ_TURTLE = "turtle"
SIGN_JZ_CHERRY = "cherry"
SIGN_JZ_SUN = "sun"
SIGN_JZ_BAMBOO = "bamboo"
SIGN_JZ_BUFFALO = "buffalo"
SIGN_JZ_LOTUS = "lotus"
SIGN_JZ_BRIDGE = "bridge"
SIGN_JZ_PEBBLE = "pebble"
SIGN_JZ_CAESAR = "caesar"
SIGN_JZ_EMPRESS = "empress"
SIGN_JZ_MOON = "moon"

# Native American Signs
NA_NAME = "Native American Signs"
SIGN_NA_FALCON = "falcon"
SIGN_NA_BEAVER = "beaver"
SIGN_NA_DEER = "deer"
SIGN_NA_WOODPECKER = "woodpecker"
SIGN_NA_SALMON = "salmon"
SIGN_NA_BEAR = "bear"
SIGN_NA_RAVEN = "raven"
SIGN_NA_SNAKE = "snake"
SIGN_NA_OWL = "owl"
SIGN_NA_GOOSE = "goose"
SIGN_NA_OTTER = "otter"
SIGN_NA_WOLF = "wolf"

# Egyptian Signs
E_NAME = "Egyptian Signs"
SIGN_E_NILE = "nile"
SIGN_E_AMUNRA = "amunra"
SIGN_E_MUT = "mut"
SIGN_E_GEB = "geb"
SIGN_E_OSIRIS = "osiris"
SIGN_E_ISIS = "isis"
SIGN_E_THOTH = "thoth"
SIGN_E_HORUS = "horus"
SIGN_E_ANUBIS = "anubis"
SIGN_E_SETH = "seth"
SIGN_E_BASTET = "bastet"
SIGN_E_SEKHMET = "sekhmet"

# Celtic Signs
C_NAME = "Celtic Signs"
SIGN_C_ROWAN = "rowan"
SIGN_C_ASH = "ash"
SIGN_C_ALDER = "alder"
SIGN_C_WILLOW = "willow"
SIGN_C_HAWTHORN = "hawthorn"
SIGN_C_OAK = "oak"
SIGN_C_HOLLY = "holly"
SIGN_C_HAZEL = "hazel"
SIGN_C_VINE = "vine"
SIGN_C_IVY = "ivy"
SIGN_C_REED = "reed"
SIGN_C_ELDER = "elder"
SIGN_C_BIRCH = "birch"
